### ISSUE TITLE
Does this code only rely on the fact that the attacker knows the IV?

### ISSUE THREAD

**Issue by secrnd** [kelalaka153/CBC-Bit-Flipping-Attack#2]
I'm wondering if this code only works if the IV is prepended to the ciphertext. 
1. I made the iv a global variable and removed it from the encrypt/decrypt data. So now only the ciphertext is passed as data. 
2. Removed padding and changed msg to "12345678901234561234567890123456" (the first error I got was the Padding error)
3. Now I'm getting random plaintext no matter how I call the bitFlip method. 

Am I missing something?

**Comment by kelalaka153** [comment]
This code is made for only a small demonstration of the danger of the bit-flipping attack on CBC

The code plays on the IV since this is the simple and effective one to show the attack ( green case).

If you remove the padding, then Crypto.Cipher's CBC decryption will fail highly. I don't see a reason to remove the padding. In CBC mode a reversible padding is a must.

You are one the red case, this means that the corresponding block will be garbage with high probability and the next block will have only one bit changed. 


Keep in mind that the code flips bytes.  I did not want to dive into the bits, so I chose the bytes at that time.

**Comment by secrnd** [comment]
First of all, great demonstration and explanation! It's really helpful. My point is that the bit-flipping attack is only dangerous if it produces a meaningful plaintext. In your example, if 5000 is changed to 1000 it makes sense and that's why it's dangerous. But if the attack produces random binary codes it misses the point in my opinion. Can the red case produce a meaningful plaintext?

**Comment by secrnd** [comment]
I was mainly looking at the code. The Stock Exchange thread describes the difference between the red and green cases perfectly. Thanks for the additional info!
